### PR TITLE
z80asm: DEFS can now be partially filled with a string

### PR DESCRIPTION
**Pull request by o-marshmallow**
The purpose of this PR is to add the possibility to (partially) fill a space defined with `DEFS` from a given string.
This becomes very handy when defining arrays of strings or arrays of more complex elements, which contain strings.
For example:
```
entries_array:
    ; First entry
    DEFS 10, "name_1st"
    DEFW point_to_first_entry
    ; Second entry
    DEFS 10, "name_2"
    DEFW point_to_second_entry 
    [...]
```
Without this `DEFS`, we have to manually specify (or generate) the number of 0s to add to the name when defined with `DEFM`:
```
entries_array:
    ; First entry
    DEFM  "name_1st", 0, 0
    DEFW point_to_first_entry
    ; Second entry
    DEFM "name_2", 0, 0, 0, 0
    DEFW point_to_second_entry 
    [...]
```

The header files have been generating by executing `make -f dev/Makefile` from `src/z80asm` directory

### CODE REVIEW

**Comment by pauloscustodio** [comment]
@o-marshmallow thanks for contributing.
I've accepted the PR with some minor changes - the filler byte option from the command line is now respected and the error message is slightly different. I've also added tests and documentation.

**Comment by o-marshmallow** [comment]
Hi @pauloscustodio ,
Thanks for your quick feedback, I wasn't quiet sure about the best formulation for the error message, but it is much better now after your modifications. Is there any particular procedure to follow to update the documentation along with a PR?

**Comment by pauloscustodio** [comment]
The documentation in in the directory z88dk/doc, file z80asm.txt. It is rather outdated, unfortunately. I've added a short paragraph explaining the new DEFS syntax.

**Comment by o-marshmallow** [comment]
@pauloscustodio Thanks for the tip, I used to always refer to the wiki :+1:

**Pull request closed without merging**
