### PR TITLE
classic - lib3d add homogeneous coordinate matrix operations

### PR DESCRIPTION
**Pull request by feilipu**
Add homogeneous coordinate matrix operations.
For #2099

Still need to update the Makefile to build the library with floating maths point at some stage.

The new vector and matrix operations won't work properly with fixed point maths, but this won't affect the previous functions' performance.

### Vector 4d functions

- unit_v
- dot_v
- mult_v
- scale_v

### Matrix 4d functions

- identity_m
- mult_m
- rotx_m
- roty_m
- rotz_m
- scale_m
- shear_m
- translate_m
- projection_opengl_m
- projection_w3woody_m

### CODE REVIEW

**Comment by zx70** [comment]
what does the integet->float->integer conversion do?

**Comment by feilipu** [comment]
There is an `i2f()` and `f2i()` that I believe creates a 24.8bit fixed point number (as a long) from a 16bit integer, and the reverse operation. Used in the existing functions, but not in my float based new additions. 

But otherwise I'm not sure what your question relates to?

**Comment by zx70** [comment]
you're totally right,  i2f is not dealing with floats!   sorry it was too long ago

**Comment by feilipu** [comment]
@zx70

But, looking at it again this morning, I am a bit confused about how the fixed point conversions are working.

I see that `f2i()` is actually converting 26.6 (one byte right, two bits left) to `int`.
And `i2f()` does the reverse (one byte left, two bits right with sign extension) `int` to 26.6 fixed point.

So I've changed some of the `#define` because they looked wrong.

 `divfx()` didn't convert back to `int` after the division. Neither did `sqrtfx()`
I've added a `f2i()` to each definition.

But I didn't change the `mulfx()` and `sqrfx()` that look to me like they need to have a left shift of 3 (multiply by 8) to make a correct 26.6 fixed point, which is then converted back to `int`. Or just drop the conversion `f2i()` conversion, as `int` * `int` is still an `int`.

Perhaps I'm not getting their operations correct?
And getting confused about what they should be doing?

```asm
; before
#define mulfx(x,y)	f2i((long)y * (long)x)
#define divfx(x,y)	(i2f(x)/(long)y)
#define sqrfx(x)	(f2i((long)x * (long)x))
#define sqrtfx(x)	(((long)(sqrt(x)))*8)
```

```asm
; now
#define mulfx(x,y)	(f2i((long)(x * y)))
#define divfx(x,y)	(f2i(i2f(x)/y))
#define sqrfx(x)	(f2i((long)(x * x)))
#define sqrtfx(x)	(f2i(((long)(sqrt(x)))*8))
```

**Comment by zx70** [comment]
IIRC this trick is from the Rafael's MSX library,  
For what I could understand it was a way to do a little bit of rounding in the scaling operations and reduce the precision loss due to the integer values.

**Comment by feilipu** [comment]
Hmm. So they seem to only be used within the `lib3d` library. It is possible that they are not totally compliant with their own specification, and what I see as "errors" cancel out when they are used as a pair.

I'll look a bit harder to understand.

**Comment by zx70** [comment]
Yes, for what i could understand it's simply a quick way to multiply the operators by two (thus, sometimes it is sufficient to do it only on one of the parameters).    Later on, a division by two will happen.

**Comment by feilipu** [comment]
So `divfx()` leaves its result as a 26.6 fixed, and in `examples/msx/ex1.c` and `examples/msx/ex9.c` the final `f2i()` conversion is done in the calling function. Which explains why it is missing from the `#define`. Don't know why that was the chosen path.
There's no reason to leave it "wrong", so I'll fix it.

The `mulfx()` should have one conversion to 26.6, so that the binary point is in the correct place. Currently it doesn't have that, so the conversion back to integer moves the binary point 6 places for no reason.<br>Corrected `#define mulfx(x,y)	(f2i(i2f(x)*y))`

Similarly `sqrfx()` has the binary point in the wrong place.<br>Corrected `(f2i(i2f(x)*x))`

But actually the functions that use `mulfx()` or `sqrfx()` would be better just using integer multiplies. There's no accuracy lost in a multiply, and it saves the conversion overhead and reduces the multiply to integer rather than long. Basically, I've put them back to use the commented out code.

And, it is the same for `divfx()` as there's no benefit from using `long` fixed point because the intermediate values are all handled as integers. So I returned returned to the original commented out code. It will be 4x faster doing normal integer divides rather than long fixed point divides.

**Comment by zx70** [comment]
Thank you, it looks better.    At the time I focused on the surface drawing (the 'stencil' stuff) and dumbly converted the original i2f/f2i macros into functions but didn't focus on the real effectiveness of the long<>int conversion job, I just kept them in working order.
There could be a generic variant of those demos, but I woudn't care in this stage.
As you can see they're few examples not very linear and IMO nobody tried to use the library in depth in the past years.
Thus a bit of housekeeping is for the best  :)

**Comment by feilipu** [comment]
I'll merge this and follow up with a make recipe for the floating point functions later.

**Pull request merged**
