### PR TITLE
zsdcc - update to v4.0.0

### PR DESCRIPTION
**Pull request by feilipu**
Quite [a few bug fixes and some minor improvements in z80 code](https://sourceforge.net/p/sdcc/code/HEAD/tree/trunk/sdcc/ChangeLog) from v3.9.1 r11311.

v3.9.5 r11480 - has some new bug fixes.

__EDIT__ v4.0.0 released on 30 January 2020. So hold this until then. [Release schedule](https://sourceforge.net/p/sdcc/wiki/SDCC%204.0.0%20Release/).

### CODE REVIEW

**Comment by suborb** [comment]
[slight delay]

Let me try to create the win32/osx builds before we merge this one.

**Comment by feilipu** [comment]
No rush. Just put it up here prospectively, waiting for a next "stable" release.
There's also the bug #1279 that should be fixed before we do anything.

I'm now using this version, to see if I get issues. So far so good.

**Comment by feilipu** [comment]
_What’s in a name? That which we call a rose,
By any other name would smell as sweet._

It is called v4.0.0, and so it must be v4.0.0?

**Comment by feilipu** [comment]
@suborb could you have a look at the win32/osx builds, please?
Final release expected in a few days.

**Comment by suborb** [comment]
@feilipu built and the nightly will now pick them up

**Comment by feilipu** [comment]
@suborb Final 4.0.0 release has dropped.
Once the win32/osx builds are done, we can merge this, and it is done.

**Comment by suborb** [comment]
Updated. They report as:

Build: 4.0.0 #11528 (Mac OS X x86_64) Jan 30 2020

**Comment by feilipu** [comment]
Thanks. Yes I see the same version report. So I selected [r11535](https://sourceforge.net/p/sdcc/code/11535/)  as the "final" as that was the tag with news tag.

**Pull request merged**
