### PR TITLE
Issue #1391: Parallel builds for newlib

### PR DESCRIPTION
**Pull request by suborb**
config_private.inc moved to `target/obj` and added to various include paths.

makefile rewritten to allow all libraries to be build in parallel. Shortcuts added: `make [target]` to build the library for that target.

Moving some of the classic crt0 files into the newlib directory structure.

@feilipu do you mind have a check that the libraries are still generated properly.

### CODE REVIEW

**Comment by pauloscustodio** [comment]
> I've added on -d to z80asm, but I'm not sure it works with the -O option to z80asm

@suborb, I confirm that -d works with -O.

Note that -d only compares the timestamp of the source and object file and will fail to recognize a need to build if an included file is changed or if a -D option is different.

**Comment by suborb** [comment]
Yes, I spotted that it worked the way I expected when I applied it to classic - because the build time is shorter, it's easier to see the reduced build time.

**Comment by feilipu** [comment]
I'm seeing this at the moment.
Will have a deeper look soon.
```
m4 -DCFG_ASM_DEF target/cpm/config.m4 > target/cpm/config_cpm_private.inc
m4 -DCFG_ASM_PUB target/cpm/config.m4 > target/cpm/config_cpm_public.inc
m4 -DCFG_C_DEF target/cpm/config.m4 > target/cpm/config_cpm.h
cp target/cpm/config_cpm_private.inc target/cpm/obj/config_private.inc
z80asm  -d -Otarget/cpm/obj/sccz80 -Itarget/cpm/obj -xlib/sccz80/cpm -I/home/phillip/Z80/z88dk/libsrc/_DEVELOPMENT//../../lib/ @target/cpm/library/cpm_sccz80.lst
Error at file 'target/cpm/driver/terminal/cpm_00_input_cons/cpm_00_input_cons_ichar_msg_getc.asm' line 61: symbol '__CPM_RCOB' not defined
Error at file 'target/cpm/driver/terminal/cpm_01_input_kbd_dcio/cpm_01_input_kbd_dcio_iterm_msg_getc.asm' line 20: symbol '__CPM_DCIO' not defined
Error at file 'target/cpm/driver/terminal/cpm_01_output_dcio/cpm_01_output_dcio_iterm_msg_bs.asm' line 18: symbol '__CPM_DCIO' not defined
Error at file 'target/cpm/driver/terminal/cpm_01_output_dcio/cpm_01_output_dcio_iterm_msg_bs.asm' line 24: symbol '__CPM_DCIO' not defined
Error at file 'target/cpm/driver/terminal/cpm_01_output_dcio/cpm_01_output_dcio_oterm_msg_bell.asm' line 21: symbol '__CPM_DCIO' not defined
Error at file 'target/cpm/driver/terminal/cpm_01_output_dcio/cpm_01_output_dcio_oterm_msg_putc.asm' line 67: symbol '__CPM_DCIO' not defined
Error at file 'target/cpm/driver/character/cpm_00_input_reader/cpm_00_input_reader_ichar_msg_getc.asm' line 20: symbol '__CPM_RRDR' not defined
Makefile:111: recipe for target 'lib/sccz80/cpm.lib' failed
make: *** [lib/sccz80/cpm.lib] Error 1
make: Leaving directory '/home/phillip/Z80/z88dk/libsrc/_DEVELOPMENT'
```

**Comment by feilipu** [comment]
Also, missing individual builds.
```
phillip@SilverQuad:~/Z80/z88dk$ cd libsrc/_DEVELOPMENT/
phillip@SilverQuad:~/Z80/z88dk/libsrc/_DEVELOPMENT$ make job-yaz180
make: *** No rule to make target 'job-yaz180'.  Stop.
phillip@SilverQuad:~/Z80/z88dk/libsrc/_DEVELOPMENT$ make job-rc2014
make: *** No rule to make target 'job-rc2014'.  Stop.
phillip@SilverQuad:~/Z80/z88dk/libsrc/_DEVELOPMENT$ make job-m
make: *** No rule to make target 'job-m'.  Stop.
phillip@SilverQuad:~/Z80/z88dk/libsrc/_DEVELOPMENT$ make job-hbios
make: *** No rule to make target 'job-hbios'.  Stop.
```

**Comment by suborb** [comment]
I didn’t put the job- tasks in. It’s just make yaz180 etc. Easy to read to restore if needed though.

**Pull request merged**
