### PR TITLE
Add a -trace flag to ticks

### PR DESCRIPTION
**Pull request by pauloscustodio**
Add a -trace flag to run ticks in trace mode, showing the registers, flags and disassembly on stdout.

### CODE REVIEW

**Comment by suborb** [comment]
I already added a trace command to the debugger. It's probably nicer to fold the two features together rather than have two different implementations.

**Comment by pauloscustodio** [comment]
My need was to run the ticks with a -trace flag and no manual intervention, and to analyze the output for the unwanted changes in the flags. You can ditch my changes if this is done some other way.

**Comment by suborb** [comment]
I'll fold it in so that -trace uses the debugger version - and still runs without intervention.

**Comment by pauloscustodio** [comment]
Works perfectly. Thanks!

**Pull request merged**
