### PR TITLE
Fix 396: build lstmanip in Visual Studio

### PR DESCRIPTION
**Pull request by pauloscustodio**
Had to pull-in the getopt.c implementation.

### CODE REVIEW

**Comment by suborb** [comment]
Thanks for doing this. My windows8 tablet can barely cope with notepad, I daren't try Visual studio!

In the makefile I just referred to the version in z80nm. Maybe we should hoist them to src/win32 and reference that way though?

**Comment by pauloscustodio** [comment]
I agree. I will do it.

**Comment by suborb** [comment]
Thanks for doing this @pauloscustodio

**Comment by suborb** [comment]
Travis is struggling with mac builds again, but this passed linux so merging.

**Pull request merged**
