### PR TITLE
Added Iskra Delta Partner to appmake target cpmdisk.

### PR DESCRIPTION
**Pull request by tstih**
Added Iskra Delta Partner as a target.

### CODE REVIEW

**Comment by suborb** [comment]
Do you mind also adding a SUBTYPE to cpm.cfg (https://github.com/z88dk/z88dk/blob/master/lib/config/cpm.cfg) 

For example svi, dmv are disc only SUBTYPEs

**Comment by tstih** [comment]
Sure. I'll add the sub-type. How do we proceed? Do you reject this pull request and I create another one when prepared?

**Comment by suborb** [comment]
Just add it into your branch and this PR will update.

**Comment by tstih** [comment]
Yes, but nobody merge it please. :)

**Comment by suborb** [comment]
> Yes, but nobody merge it please. :)

I've marked it as draft to indicate that it's a work in progress and blocks merging. When you're finished click the "Ready for Review" button

image

**Comment by suborb** [comment]
@tstih I'm trying to have a bit of cleanup of issues/prs etc.

Given that this is pretty simple one, I've just incorporated it directly. Thanks for the contribution.

**Pull request closed without merging**
