### PR TITLE
Fix #1626 - CI on Github actions and azure pipelines

### LINKED ISSUE #1626: (build) Migrating away from travis
Nothing is for free, and waiting for travis to build isn't costless either.

Since the recent changes, the Linux build queue for travis is regularly 5-6k jobs which results in a very long wait time.

Need to take a look at the alternatives, circleci, travis, cheeky gitlab mirror, GitHub actions. I'm not adverse to running an agent locally on my vm server as long as it can be secured.

### PR DESCRIPTION
**Pull request by pauloscustodio**

### CODE REVIEW

**Comment by suborb** [comment]
@pauloscustodio don't feel wedded to the ubuntu 16.04 - I only picked that since it matched what was in travis.

**Comment by pauloscustodio** [comment]
@suborb, Ubuntu is fine, the change to use an older Template version was very minor.

I am ripping my few left hairs with Azure, though! Can't get the script to hold on the environment variables set by perl local::lib

**Comment by suborb** [comment]
Maybe it's time to cheat?

Add an option into build.sh to set the perl local variable?

**Comment by pauloscustodio** [comment]
> Maybe it's time to cheat?

I like your thinking! Let's find out...

**Pull request closed without merging**
