### PR TITLE
Fix color escape codes on Windows

### PR DESCRIPTION
**Pull request by empathicqubit**

### CODE REVIEW

**Comment by suborb** [comment]
What does this do exactly? I was under the impression that cmd.exe already understood vt100 codes?

**Comment by empathicqubit** [comment]
It does, but you have to turn it on first.

**Comment by empathicqubit** [comment]
clers
terminal
pwsh

**Comment by empathicqubit** [comment]
So this fixes all of them. It also fixes it in VSCode which is the only one I actually care about. There is still a problem where the arrows won't work in Git Bash or VSCode.

**Comment by suborb** [comment]
Ah cool, thank you for the code + explanation!

**Pull request merged**
