### PR TITLE
m32 - rounding improvements

### PR DESCRIPTION
**Pull request by feilipu**
- Adjusted rounding on the `_fsinv` (`_fsdiv`), and `_fsinvsqrt` (`_fssqrt`) functions to ensure clean integer returns (where relevant).
- Adjusted rounding on the `_fsmul` function to recognise that "correct" calculation of carry in from the least significant byte has already been incorporated (unlike the digi international multiply), so only the most significant rounding bit should be considered.
- Minor whitespace, comment, and readme updates.

Noted, that the newlib has a fudge factor built into the printf `%f` conversion, so things are not always what they seem. And, also noted that this fudge factor seems to be wrong sometimes when presented with a correct representation which it wrongly interprets.

### CODE REVIEW

**Comment by suborb** [comment]
There's another issue in fsconv BTW:

```
; now convert long in dehl to float in dehl
 .m32_float32		 .m32_float32
     ex de,hl                    ; hlde		     ex de,hl                    ; hlde
+     ld  b,0			; clear sign
     bit 7,h                     ; test sign, negate if negative		     bit 7,h                     ; test sign, negate if negative
     jr Z,dldf0		     jr Z,dldf0
     ld b,h                      ; to hold the sign, put copy of MSB into b		     ld b,h                      ; to hold the sign, put copy of MSB into b
```

**Comment by feilipu** [comment]
Ok.
Also just fixing the sqrt function to break with negative numbers. Currently it swallows them whole.

**Comment by suborb** [comment]
Thanks Phillip, I'll try this out this evening and hopefully we'll be there. Hopefully this will get the last bit into the mantissa to make results "correct"

I was wondering about the IEEE->math48 conversion in newlib as to whether it was doing some rounding in the process - I've been dumping out the hex bytes and using an online converter to validate.

**Comment by feilipu** [comment]
I see the newlib printf `%f` conversion playing tricks on me...

```c
union floatlong
{
    float f;
    int32_t l;
};

void main(void)
{
    uint16_t n;
    union floatlong resulta_m32, resultd_m32, result_m48;
    float floatl, floatr;

    for (n = 1; n <= 255; n+=1)
    {
        floatl = (float)n;
        floatr = (float)n;

        result_m48.f = floatl*floatr;

        resulta_m32.f = fssqr(floatr);
        resultd_m32.f = fsdiv(floatl,floatr);

        printf("float %u m48: %f m32a: %f m32d: %f\r\n", n, result_m48.f, resulta_m32.f, resultd_m32.f);
        printf("float %u m48: %lx m32a: %lx m32d: %lx\r\n\n", n, result_m48.l, resulta_m32.l, resultd_m32.l);
    }
}
```
IEEE **0x47d4b200** most accurate representation => **108900**

```sh
float 330 m48: 108899.999990 m32a: 108899.999990 m32d: 1.000000
float 330 m48: 47d4b200 m32a: 47d4b200 m32d: 3f800000

float 367 m48: 134688.999990 m32a: 134689.015620 m32d: 1.000000
float 367 m48: 48038840 m32a: 48038841 m32d: 3f800000

float 404 m48: 163215.999990 m32a: 163215.999990 m32d: 1.000000
float 404 m48: 481f6400 m32a: 481f6400 m32d: 3f800001

float 441 m48: 194480.999990 m32a: 194481.015620 m32d: 1.000000
float 441 m48: 483dec40 m32a: 483dec41 m32d: 3f7fffff

float 478 m48: 228483.999990 m32a: 228483.999990 m32d: 1.000000
float 478 m48: 485f2100 m32a: 485f2100 m32d: 3f800001
```

**Pull request merged**
