### PR TITLE
sccz80 - 8085 arch optimisation rules

### PR DESCRIPTION
**Pull request by feilipu**
Working on #2179 

Initially a hack into `zcc.c` to set `COPTRULESCPU` to run COPT the 8085 `arch/8085/8085_rules.1` file before the `-opt-code-speed` `z80_rules.8` file. This hack needs to be backed out and replaced with a proper all platform setting to work with all CPU types based on the `-m` command line option.

### CODE REVIEW

**Comment by suborb** [comment]
Do we not just need an options that set c_coptrules_cpu and c_coptrules_sccz80 from the command line so that we can deal with multi-cpu targets?

That way single architecture targets can just rely on the `COPTRULES` config options and we can override them on a per subtype/clib basis for the different cpus.

**Comment by feilipu** [comment]
> Do we not just need an options that set c_coptrules_cpu and c_coptrules_sccz80 from the command line so that we can deal with multi-cpu targets?

IMHO, there's no need to yet add another command line option. The `-m` machine type already discerns the correct arch `arch-rules.1` file to be run. It is just a matter of populating the `c_coptrules_cpu` with a string pointing to the correct arch file.

As an extension (totally not suggesting this, but it would be possible), there is also a target specific optimisation file foreseen in zcc, which could be populated by a file somewhere standardised in the target directory, which could cover target custom opcodes, etc.

Then that leaves the user opt file free to be added from the command line.

All of these above are run before the `-opt-code-speed` related rules too.

**Comment by suborb** [comment]
> IMHO, there's no need to yet add another command line option. The `-m` machine type already discerns the correct arch `arch-rules.1` file to be run. It is just a matter of populating the `c_coptrules_cpu` with a string pointing to the correct arch file.

Good point!

> As an extension (totally not suggesting this, but it would be possible), there is also a target specific optimisation file foreseen in zcc, which could be populated by a file somewhere standardised in the target directory, which could cover target custom opcodes, etc.

I think I added this in, in case there was a target where, for example l_gint is implemented by a rst

**Comment by feilipu** [comment]
> It is just a matter of populating the `c_coptrules_cpu` with a string pointing to the correct arch file

The reason that I'm not doing this is that I don't know that I can get the machine type and directory creation string parsing / tokenisation across all win/linux/macos platforms anywhere close to correct. Best to leave this to experts. :smile:

**Comment by feilipu** [comment]
Ok, now the rules are moved over, with no optimisation regression.
`-O0` is actually much better, as the `ld de,sp+%1` opcodes are picked up.

Let's see if things can be tided and rationalised.

**Comment by feilipu** [comment]
Ok. Pending the changes to `zcc.c` this is done.
- removes special opt handling in config files
- removes 8085 specifics out of `z80_rules.1`
- adds 8085 specifics into `arch/8085/8085_rules.1`

**Comment by suborb** [comment]
I'm working on the zcc bit which I'll merge into this branch before merging the whole lot together.

**Comment by suborb** [comment]
I've finished tinkering for the evening now.

The --opt-code-speed options actually seem to slow down the resulting binary now - I get the best results for z80 with just a plain -O2.

**Comment by feilipu** [comment]
> I've finished tinkering for the evening now.

I've finished on this too, so I'll merge it once it has passed CI.

I [rebuilt CP/M-IDE for 8085](https://github.com/RC2014Z80/RC2014/commit/c1361da93ba321c6254cbe05be7d31a72e71319b?diff=split) yesterday, and found that the resulting binaries to be over 400 bytes smaller. This reduction comes from the [FATFS library](https://github.com/feilipu/z88dk-libraries/tree/master/ff/rc2014/lib/newlib/sccz80) mainly, [with 337 bytes](https://github.com/feilipu/z88dk-libraries/commit/144564019b9a7293a95cf6df6cf5a72239b99096), but also a small amount from the [shell](https://github.com/RC2014Z80/RC2014/blob/master/ROMs/CPM-IDE/acia85/main.c). The 8085 binaries (at 75.7kB) are now substantially smaller than equivalent functionality z80 binaries (at 79.9kB). So I think we've squeezed quite enough blood out of that rock for now. 😉

If I get time over the week, I'll rerun some benchmarking to see how the changes reflect in those numbers.

**Comment by feilipu** [comment]
Closes #2179

**Pull request merged**
