### PR TITLE
arkos tracker support (newlib)

### PR DESCRIPTION
**Pull request by jorgegv**
Add Arkos Tracker support for Newlib compilations (SCCZ80 and SDCC)

### CODE REVIEW

**Comment by jorgegv** [comment]
Ah, great. I was just going to ask what needed to be done just to be sure, but there you are.

**Comment by jorgegv** [comment]
Hey @suborb I have done al the points 1 to 7, but I'm getting an error, the build does not complete. Apparently it's during compilation of Altair_8800 library, but I'm not quite familiar (yet) with hot the newlib compiles work. Here is the error (as you can see, the files that the error says do exist):

```
(...)
--- Building Altair8800 Library ---

zsock/fopen_zsock.c:47:28: warning: Assigning 'ptr', type: unsigned char uint8_t* ptr from char *  [-Wincompatible-pointer-types]
XSetStandardProperties.c:28:13: warning: Converting type: char * _Xsmallfont*  to char * font [-Wincompatible-pointer-types]
XSetStandardProperties.c:28:13: warning: Converting type: char * _Xsmallfont*  to char * font [-Wincompatible-pointer-types]
XSetStandardProperties.c:28:13: warning: Converting type: char * _Xsmallfont*  to char * font [-Wincompatible-pointer-types]
XSetStandardProperties.c:28:13: warning: Converting type: char * _Xsmallfont*  to char * font [-Wincompatible-pointer-types]
XSetStandardProperties.c:28:13: warning: Converting type: char * _Xsmallfont*  to char * font [-Wincompatible-pointer-types]
XSetStandardProperties.c:28:13: warning: Converting type: char * _Xsmallfont*  to char * font [-Wincompatible-pointer-types]
XSetStandardProperties.c:28:13: warning: Converting type: char * _Xsmallfont*  to char * font [-Wincompatible-pointer-types]
error: pattern returned no files: /home/jorgegv/src/spectrum/z88dk-jorgegv/libsrc/_DEVELOPMENT//sound/ay/c/sccz80/arkos/*.asm /home/jorgegv/src/spectrum/z88dk-jorgegv/libsrc/_DEVELOPMENT//sound/ay/z80/arkos/*.asm
make[3]: *** [Makefile:23: obj/newlib-z80] Error 1
make[2]: *** [Makefile:41: arkos] Error 2
make[1]: *** [Makefile:14: ay] Error 2
make: *** [Makefile:1796: altair8800_clib.lib] Error 2
make: se sale del directorio '/home/jorgegv/src/spectrum/z88dk-jorgegv/libsrc'
 jorgegv@endor  z88dk-jorgegv   arkos_support_newlib  🐧  ls /home/jorgegv/src/spectrum/z88dk-jorgegv/libsrc/_DEVELOPMENT//sound/ay/c/sccz80/arkos/*.asm
/home/jorgegv/src/spectrum/z88dk-jorgegv/libsrc/_DEVELOPMENT//sound/ay/c/sccz80/arkos/ply_akg_init.asm
/home/jorgegv/src/spectrum/z88dk-jorgegv/libsrc/_DEVELOPMENT//sound/ay/c/sccz80/arkos/ply_akg_initsoundeffects.asm
/home/jorgegv/src/spectrum/z88dk-jorgegv/libsrc/_DEVELOPMENT//sound/ay/c/sccz80/arkos/ply_akg_play.asm
/home/jorgegv/src/spectrum/z88dk-jorgegv/libsrc/_DEVELOPMENT//sound/ay/c/sccz80/arkos/ply_akg_playsoundeffect.asm
/home/jorgegv/src/spectrum/z88dk-jorgegv/libsrc/_DEVELOPMENT//sound/ay/c/sccz80/arkos/ply_akg_stop.asm
/home/jorgegv/src/spectrum/z88dk-jorgegv/libsrc/_DEVELOPMENT//sound/ay/c/sccz80/arkos/ply_rom_akg_init.asm
/home/jorgegv/src/spectrum/z88dk-jorgegv/libsrc/_DEVELOPMENT//sound/ay/c/sccz80/arkos/ply_rom_akg_initsoundeffects.asm
/home/jorgegv/src/spectrum/z88dk-jorgegv/libsrc/_DEVELOPMENT//sound/ay/c/sccz80/arkos/ply_rom_akg_play.asm
/home/jorgegv/src/spectrum/z88dk-jorgegv/libsrc/_DEVELOPMENT//sound/ay/c/sccz80/arkos/ply_rom_akg_playsoundeffect.asm
/home/jorgegv/src/spectrum/z88dk-jorgegv/libsrc/_DEVELOPMENT//sound/ay/c/sccz80/arkos/ply_rom_akg_stop.asm
 jorgegv@endor  z88dk-jorgegv   arkos_support_newlib  🐧  ls /home/jorgegv/src/spectrum/z88dk-jorgegv/libsrc/_DEVELOPMENT//sound/ay/z80/arkos/*.asm
/home/jorgegv/src/spectrum/z88dk-jorgegv/libsrc/_DEVELOPMENT//sound/ay/z80/arkos/asm_arkos_msx_rom.asm  /home/jorgegv/src/spectrum/z88dk-jorgegv/libsrc/_DEVELOPMENT//sound/ay/z80/arkos/asm_arkos_zx_rom.asm
/home/jorgegv/src/spectrum/z88dk-jorgegv/libsrc/_DEVELOPMENT//sound/ay/z80/arkos/asm_arkos_msx_smc.asm  /home/jorgegv/src/spectrum/z88dk-jorgegv/libsrc/_DEVELOPMENT//sound/ay/z80/arkos/asm_arkos_zx_smc.asm
```

Any help would be very appreciated.

**Comment by suborb** [comment]
```
--- a/libsrc/psg/ay/arkos/Makefile
+++ b/libsrc/psg/ay/arkos/Makefile
@@ -7,7 +7,7 @@ include ../../../Make.config

 TARGET ?= test

-NEWLIBGLOBS := "$(NEWLIB_DIRECTORY)/sound/ay/c/sccz80/arkos/*.asm $(NEWLIB_DIRECTORY)/sound/ay/z80/arkos/*.asm"
+NEWLIBGLOBS := "$(NEWLIB_DIRECTORY)/sound/ay/c/sccz80/arkos/*.asm" "$(NEWLIB_DIRECTORY)/sound/ay/z80/arkos/*.asm"
 NEWLIB_TARGETS := obj/newlib-z80 obj/newlib-z80n obj/newlib-ixiy

 space :=
```

Note the placement of the double quotes!

**Comment by jorgegv** [comment]
> Note the placement of the double quotes!

Indeed! What a silly mistake :-) Thanks.

> Edit: Also, I'm not sure that there should be anything in `$(NEWLIB_DIRECTORY)/sound/ay/z80/arkos` since the arkos player is machine specific and you'll end up with a symbol clash.
> 
Yes, I have seen it now. I assumed that since the file names were different, the symbols inside would be in line with the file name, but now I've seen that the symbols are the same.

> I think the zx variants should go into `_DEVELOPMENT/arch/zx/arkos` (or similar). There's no +msx in newlib so they can be omitted.

I'll do it.

**Comment by suborb** [comment]
> Indeed! What a silly mistake :-) Thanks.

NW, it's one of those "blind" things, where you just can't see the problem!
 
> Edit: Also - The +cpc also can be omitted, right? newlib is also not available for +cpc according to docs (and to sources, from what I've seen...)

Correct, so it'll just be for +zx and +zxn should be able to reference it as well.

**Comment by jorgegv** [comment]
OK, build works now and I believe files are correctly in place. On with the examples (and the fixes that will surely come from them :-) )

**Comment by jorgegv** [comment]
Reorganization and file movements seem OK at least for Classic. All examples compile successfully, and the ZX ones also work without issues (tested).

**Comment by jorgegv** [comment]
After fixing some more things ZXNext related, everything seems to work fine. I think It is really for merging, @suborb .

I'm removing the WIP from the PR title.

P.s.: indeed it's much more complicated to integrate something with Newlib than Classic!

**Comment by suborb** [comment]
> After fixing some more things ZXNext related, everything seems to work fine. I think It is ready for merging, @suborb .

Thank you for battling through on this one. I think it gets easier the second time! 

Just one little "minor" fix up, normally the sdcc_ix and sdcc_iy variants don't use the `__smallc` calling convention.

> P.s.: indeed it's much more complicated to integrate something with Newlib than Classic!

Yes, there's a lot more files about the place that are almost, but not quite the same!

**Comment by jorgegv** [comment]
> Thank you for battling through on this one. I think it gets easier the second time!
> 

Indeed. I would like to share with you my notes for adding/porting software to Classic/Newlib, how can we do it? I'd like you to review and add anything missing to it (if you don't mind). May I suggest to add a new document? Maybe a new PR?

> Just one little "minor" fix up, normally the sdcc_ix and sdcc_iy variants don't use the `__smallc` calling convention.
> 

I have done it and everything compiles and runs OK. But I had to remove the `__LIB__` from the .h file in `proto` (SDCC would not compile it otherwise), but then I had to manually tweak `include/_DEVELOPMENT/sccz80/sound/arkos.h` to have the `__LIB__` decorators again.

Can we do something with the `arkos.h` file in the `proto` directory so that when creating `sdcc_ix` and `sdcc_iy` includes, no `__LIB__` is generated but it _is_ added for `sccz80`?

Otherwise, even manually tweaked, the correct files have been commited, so everything works.

**Comment by suborb** [comment]
> Indeed. I would like to share with you my notes for adding/porting software to Classic/Newlib, how can we do it? I'd like you to review and add anything missing to it (if you don't mind). May I suggest to add a new document? Maybe a new PR?

If it's documentation, let's do it on the wiki rather than in the code repository.

> I have done it and everything compiles and runs OK. But I had to remove the `__LIB__` from the .h file in `proto` (SDCC would not compile it otherwise), but then I had to manually tweak `include/_DEVELOPMENT/sccz80/sound/arkos.h` to have the `__LIB__` decorators again.

Yes, the m4 macros deal with this - take a look at `aywyz.h` - however, you might end up needing to create more stubs with different calling conventions.

Re the hack, if you just include `<sys/compiler.h>` then `__LIB__` vanishes for sdcc.

**Comment by jorgegv** [comment]
> If it's documentation, let's do it on the wiki rather than in the code repository.

Really? Can I just add content to the wiki?

> Re the hack, if you just include `<sys/compiler.h>` then `__LIB__` vanishes for sdcc.

Definitely this seems an easy approach, enough for what we have :-)

Done in 9dde3db81a8bcf35ed6c76436c2552c5fa09775a

Can merge now :)

**Comment by suborb** [comment]
> Really? Can I just add content to the wiki?

You should be able to - I think it's setup so a contributor can edit. I've created a couple stub pages:

* https://github.com/z88dk/z88dk/wiki/Classic--Adding
* https://github.com/z88dk/z88dk/wiki/NewLib--Adding

> Can merge now :)

Will do when the build storm calms down/I've fixed whatever I've broken :)

**Comment by suborb** [comment]
In it goes - thanks so much again @jorgegv

**Comment by jorgegv** [comment]
> > Really? Can I just add content to the wiki?
> 
> You should be able to - I think it's setup so a contributor can edit. I've created a couple stub pages:
> 
> * https://github.com/z88dk/z88dk/wiki/Classic--Adding
> * https://github.com/z88dk/z88dk/wiki/NewLib--Adding

There you are, in the Wiki it is.

**Pull request merged**
