### PR TITLE
zsdcc - bump to #11877 for testing

### PR DESCRIPTION
**Pull request by feilipu**
Update to a new zsdcc version. For testing to see if things are better.

Quite a few bug fixes over the past months. Perhaps some of them are relevant to z88dk.

* src/z80/gen.c: Fix bug #3105.
* src/z80/peep.c: Fix handling of ioi, ioe in peephole optimizer, including bug #3118.
* src/z80/gen.c: Fix bug #3116.
* device/lib/gbz80/abs.s, device/lib/gbz80/strlen.s: Assembler optimized abs() and strlen() for GBZ80.
* src/SDCCval.c, src/SDCCval.h, src/z80/gen.c: Fix bug #3104.
* src/z80/peeph.def: Disable some peephole rules for bug #3102.
* src/z80/gen.c: Fix bug #3101.
* src/z80/gen.c: Implement RFE #404.
* src/z80/gen.c: Small improvements for left-shift by constant expression.
* src/z80/gen.c: Improve left shift, RFE #465.
* src/z80/gen.c: Fix bug #3097.
* and it continues...

### CODE REVIEW

**Comment by suborb** [comment]
@feilipu should I perform the build duties?

**Comment by feilipu** [comment]
I haven't noticed any issues, but then I never have previously. It really needs to be tested against the problem builds in the original issue, which I can't do.

I'll move it along another r bump today to pick up a more recent bug fix, and then please build for testing when you have a opportunity, thanks.

**Comment by feilipu** [comment]
@suborb noted the `Makefile` conflicts. Please resolve as you see fit. I think you stopped building sdcc, right?

**Comment by suborb** [comment]
I'll build + sort out conflicts at the weekend.

I changed the way we get and build sdcc so that it works in a more incremental way - sf svn is so slow that the auto builds were stalling so now I have a vanilla source tarball on nightly that's downloaded for auto-builds. SVN downloading still works of course.

Effectively we have the following dependencies:

bin/zsdcc: src/sdcc-build/bin/sdcc
src/sdcc-build/bin/sdcc: src/sdcc-build/bin/Makefile
src/sdcc-build/Makefile: src/sdcc-build/configure

Configure depends on downloading a patched tarball or an svn checkout + patch.

The whole process depends on BUILD_SDCC=1 being defined. The choice between tarball/svn is based on BUILD_SDCC_HTTP=1

**Comment by suborb** [comment]
Nightly binaries have been updated, so I'll merge.

**Comment by suborb** [comment]
Found some breakage! Banked calling changed and --legacy-banking doesn't repair it.

**Pull request merged**
