### PR TITLE
TVC time() fixed for ticks of system (instead of ticks * 65536)

### PR DESCRIPTION
**Pull request by dikdom**
fix for TVC time()

### CODE REVIEW

**Comment by feilipu** [comment]
Doesn't `ld de,0` work?

**Comment by dikdom** [comment]
> Doesn't `ld de,0` work?

Bad habbit. I'll fix it soon. 
(ld de,0 is 10T, while ld d,0 ; ld e,d is 11T altogether. For some reason I thought this is faster...)

**Comment by feilipu** [comment]
Done? Or more to add?

**Comment by dikdom** [comment]
> Done? Or more to add?

Done.

**Pull request merged**
