### PR TITLE
Z80asm 8080/8085

### PR DESCRIPTION
**Pull request by pauloscustodio**
Support 8085 documented and undocumented opcodes.

Add new predefined constants for the CPU family: ```__CPU_ZILOG__``` or ```__CPU_RABBIT__``` or ```__CPU_INTEL__```

List of additional 8085 opcodes:
```
  dsub            ; 08
  sub hl, bc      ; 08

  arhl            ; 10
  rrhl            ; 10
  sra hl          ; 10

  rlde            ; 18
  rdel            ; 18
  rl de           ; 18

  rim             ; 20

  ldhi 255        ; 28 FF
  adi hl, 255     ; 28 FF
  ld de, hl+255   ; 28 FF

  sim             ; 30

  ldsi 255        ; 38 FF
  adi sp, 127     ; 38 7F
  ld de, sp+255   ; 38 FF

  ovrst8          ; CB
  rstv            ; CB

  shlde           ; D9
  shlx            ; D9
  ld (de), hl     ; D9

  lhlde           ; ED
  lhlx            ; ED
  ld hl, (de)     ; ED

  j_k 32767       ; FD FF 7F
  j_x5 32767      ; FD FF 7F
  jk 32767        ; FD FF 7F
  jx5 32767       ; FD FF 7F

  j_nk 32767      ; DD FF 7F
  j_nx5 32767     ; DD FF 7F
  jnk 32767       ; DD FF 7F
  jnx5 32767      ; DD FF 7F

```

### CODE REVIEW

**Comment by suborb** [comment]
Your summary is missing `jnk`?

**Comment by pauloscustodio** [comment]
> Your summary is missing jnk?

JNK does apparently not exists - there were no more spare opcodes, maybe?

Reference: https://electronicerror.blogspot.com/2007/08/undocumented-flags-and-instructions.html

**Comment by suborb** [comment]
0xdd is jnk in that link.

**Comment by pauloscustodio** [comment]
You're right! My mistake.

**Pull request merged**
