### PR TITLE
Implement macros

### PR DESCRIPTION
**Pull request by pauloscustodio**
z80asm is now a macro assembler!

Implemented MACRO/ENDM, REPT/ENDR, REPTC/ENDR, REPTI/ENDR, EXITM, LOCAL, DEFL, #define, #undef

Documentation at https://github.com/z88dk/z88dk/wiki/Tool---z80asm---preprocessor

### CODE REVIEW

**Comment by suborb** [comment]
That's one way to poke me to upgrade the nightly environment! 

@pauloscustodio, could you update this page: https://github.com/z88dk/z88dk/wiki/installation with the compiler requirements?

**Comment by pauloscustodio** [comment]
Done

**Comment by suborb** [comment]
With luck we should get a nightly tonight. It's being built on an completely new machine, so I've no idea if the windows build will actually work.

**Comment by suborb** [comment]
@pauloscustodio would it be possible to check in the generated files need to build the z80asm binary? 

I've sorted out the snap build, but docker is based on alpine and pulling in perl and all the deps there seems like a pain.

**Comment by pauloscustodio** [comment]
The generated files are checked in. What errors are you getting?

**Comment by pauloscustodio** [comment]
@suborb, I will have a look

**Comment by pauloscustodio** [comment]
Opened a new issue #1922

**Comment by suborb** [comment]
Sorry I fell asleep!

 I was asking whether it was possible to check in the output of the template commands - that way for a build only (no tests) Perl isn’t needed

**Comment by pauloscustodio** [comment]
The problem is solved for now with #1922. When I get to work on removing the .err files, this issue will disappear.

**Pull request merged**
