### PR TITLE
debugger_gdb.c: OpenBSD support

### PR DESCRIPTION
**Pull request by jg1uaa**
- CLOCK_MONOTONIC_RAW is for Linux, use CLOCK_MONOTONIC instead  if it is not available
- %n format of printf() raises SIGABRT on OpenBSD,  refactor with strlen()

### CODE REVIEW

**Comment by desertkun** [comment]
Can you rebase your local branch? It seems it has conflicts. It's weird %n gives a segfault, it's used like 100 times here.

Also congrats on actually using the thing, didn't see any evidence of anyone using it so far.

**Comment by desertkun** [comment]
@suborb haha thanks for reactively fixing the time issue. As per printf, I've been meaning to ditch static arrays in favor of ut_string, let me do that there as well.

**Comment by jg1uaa** [comment]
wow, how do I treat this PR?

**Comment by jg1uaa** [comment]
I do not use gdb.
But CLOCK_MONOTONIC_RAW makes compile error and printf(%n) puts warning.
Former issue is is already fixed, latter will be potential problem so I want to fix now.

**Comment by jg1uaa** [comment]
Ok, this PR is close. Thanks!

**Pull request closed without merging**
