### PR TITLE
Ignore duplicate __CDBINFO__, __C_LINE_ / __ASM_LINE_ fixes

### PR DESCRIPTION
**Pull request by desertkun**
While exploring debugging symbols support, I found several issues with debugging symbols generation.
1. When several object files are linked together, debug info about objects that they all include, collide together. See [minimal example](https://github.com/desertkun/z88dk-debug-error-minimum-example). The fix: ignore symbol redefinitions on `__CDBINFO__xxx` symbols.
2. `__C_LINE_N` and `__ASM_LINE_N` instruction do not take into account includes as well. So when an object `main.c` includes `dependency.h` and `dependency.h` happens to introduce `C_LINE` label at line 5, corresponding `C_LINE` label at `main.c:5` could no longer be defined, because such symbol already exists. Solution: add a suffix with url-encoded filename past line number, aka `__C_LINE_10_main.c` except `main.c` is url-encoded, with `%` replaced with `_`. Ticks, surprisingly, ignores anything past number on the symbol name and uses filename comment as a reference anyway.

### CODE REVIEW

**Comment by desertkun** [comment]
#1390

**Comment by suborb** [comment]
I’m away at the moment but the general principle is fine by me. 

@pauloscustodio can you review/merge etc?

**Comment by pauloscustodio** [comment]
I'm also away at the moment, and can have a look next week.

**Comment by desertkun** [comment]
@pauloscustodio I would appreciate if you could look at it. I have major ticks rework at hand that needs this to be merged first.

**Comment by pauloscustodio** [comment]
@desertkun , thanks for contributing. Merged.

**Comment by desertkun** [comment]
@pauloscustodio Thanks a lot for merging. I've got a question: I have reworked ticks in [my fork's branch](https://github.com/desertkun/z88dk/commits/ticks_gdbclient) to separate tick's debugger from tick's emulator to allow ticks to have several emulator backends, one of which would still remain tick's internal emulator, and another one would become ticks debugger on top of "gdb client". 

The question is: would you want to look at it in two stages:
1. Refactor of ticks, separate debugger from emulator, no new functionality, introduce concept of an emulator backend, of which there will be only one at that commit
2. Additional emulator backend as gdb client, which could connect to Fuse (to which I have [implementation](https://github.com/desertkun/fuse/commits/gdbserver) but would need to work with Fuse's maintainers to get that in.

Or you're fine with looking at it all at once?

Thing is in development yet, but I want to set a framework I could rely on, since I've already got a conflict. Thanks.

**Comment by pauloscustodio** [comment]
I like the two-step approach, but @suborb , this is your baby... what do you think?

**Pull request merged**
