### PR TITLE
Wrong sequence

### PR DESCRIPTION
**Pull request by polluks**
See above.

### CODE REVIEW

**Comment by aralbrec** [comment]
That code looks like a scroll.

Should it be esc[2K ?

**Comment by polluks** [comment]
delline requires scrolling
http://www.delorie.com/djgpp/doc/libc/libc_129.html

**Comment by aralbrec** [comment]
I see two or three different documentation for that vt100 escape code.

I think the most trustworthy is this:
http://www.csie.ntu.edu.tw/~r92094/c++/VT100.html

index IND             Move/scroll window up one line         ^[D
revindex RI           Move/scroll window down one line       ^[M

So what is needed is a scroll up from the current row.  Maybe ^[D is the right code if it's not full screen?
@zx70 can the ascii driver even do this?

**Comment by polluks** [comment]
Just look at the other definitions of delline in conio.h, it's a simple typo: m → M

**Comment by aralbrec** [comment]
I agree with you but I think the intended M is the wrong escape sequence.

The link you gave says delline deletes the line and scrolls the area underneath upward one row.  ^[M scrolls downward which is the wrong direction.  And I'm not sure if the vt100 driver in classic z88dk can scroll a region.  However fixing the control code to what it should be can be done now even if the driver won't interpret it correctly atm.

**Comment by polluks** [comment]
Well, I'm talking about ^[[M not ^[M
http://www.real-world-systems.com/docs/ANSIcode.html

**Comment by aralbrec** [comment]
Ah ok, that's a vt102 escape sequence.

I can see in the classic ansi driver:
https://github.com/z88dk/z88dk/blob/master/libsrc/stdio/ansi/f_ansi.asm
that ^[[M is not implemented.

It'll be ignored and not crash so it's ok to commit.

**Pull request merged**
