### PR TITLE
Increase concurrency when building libraries

### PR DESCRIPTION
**Pull request by suborb**
I _think_ I've tracked down the majority of the dependency/ordering issues when building classic.

The problems arise when building the same code for different configurations - ideally target/ code should be put into separate sub-directories, but that's a large task to tackle.

So, bump in concurrency for a couple of the CI builds - we get a nice speed bump and can enjoy any intermittent errors that come out of it.

### CODE REVIEW

**Comment by suborb** [comment]
This odd, the PR built fine, but merged and we repeatedly get this error on msys:

https://github.com/z88dk/z88dk/actions/runs/6585852909/job/17897400245

I can see that z80asm has had -v added in the past - do you have suspicions @pauloscustodio ?

**Comment by pauloscustodio** [comment]
I do not remember, and a quick search on the closed issues did not reveal anything relevant. You can try to remove the ```Z80ASM=-v``` and retest

**Comment by suborb** [comment]
Looking further, this is failing at the appmake stage and without an error message.

So, digging further, I spotted some reading beyond the bounds of an allocated block, so maybe that's triggering the equivalent of a bus error. I've pushed a fix and we'll see.

**Comment by suborb** [comment]
Obviously a bit of a heisenbug since the tixx commit before mine passed. I'll keep an eye on it.

**Pull request merged**
