### PR TITLE
8085 - add saved_hl - remove saved_de

### PR DESCRIPTION
**Pull request by feilipu**
Found compiling for 8085 using `__z88dk_callee` the `saved_hl` and `saved_de` locations are used by sccz80, but are not provided in 8085 crt0 for CP/M and other targets.

Improvement - there could be a `IF __8080 |  __8085` protection around the locations in the CP/M crt0 to create these locations only for 8080 or 8085, but I've been unable to find the right solution to make it work.

Also, additional 8080 and 8085 targets should have this added to their crt0.

### CODE REVIEW

**Comment by suborb** [comment]
I think it's `__CPU_INTEL__` that you need?

**Comment by feilipu** [comment]
> I think it's __CPU_INTEL__ that you need?

Yes. Thanks.
Added the conditional now to both cpm and test libraries.

And added to all the targets which mention 8080 or 8085 in their configuration (without the conditional).

I'll merge later if no further improvements.

**Comment by suborb** [comment]
Sorry, I'm going to mess you around.

* `saved_de` doesn't seem to be used at all so all references to it can be removed
* `saved_hl` for classic can be put into `crt_section.inc` in `bss_crt`

**Comment by feilipu** [comment]
No problem.
I guess then it can be removed from the specific classic target crt0 code?

**Comment by suborb** [comment]
> I guess then it can be removed from the specific classic target crt0 code?

Yes

**Pull request merged**
