### PR TITLE
z80-zxn - integer math routines

### PR DESCRIPTION
**Pull request by feilipu**
Integer math routines using the z80-zxn `mul de` instruction, from #481, #312, and #820.

Used the z180 `mlt de` hardware for testing purposes.

- [x] `l_mulu_16_8x8`
- [x] `l_mulu_16_16x8`
- [x] `l_mulu_16_16x16`
- [x] `l_mulu_24_16x8`
- [x] `l_mulu_32_16x16`
- [x] `l_mulu_32_32x32` (using `l0_mulu_32_32x32`)
- [x] `l_mulu_40_32x8`
- [x] `l_mulu_64_32x32` (using `l0_mulu_64_32x32`)
- [x] `l_mulu_64_64x64` (using `l0_mulu_64_32x32`and `l0_mulu_32_32x32`)
- [x] `l_mulu_72_64x8`

I dislike the z80-zxn `mul d,e` mnemonic. The incorrect implication is that `mul` is done on `e` and is stored in `d`. Whereas `mul de`, or the z180 mnemonic `mlt de`, more obviously and correctly refers to **both** the **d** and **e** registers being modified by `mul`

### CODE REVIEW

**Comment by feilipu** [comment]
Completed testing using the z180 opcode.
Next commit will revert to z80-zxn `mul d,e` opcode and enable the library to compile.

**Comment by feilipu** [comment]
@aralbrec - these are done.
But, they are not connected into the math libraries.
I can't see a clean way to do it, like #835, and the connections are messy.

**Comment by feilipu** [comment]
Done... done.

**Comment by aralbrec** [comment]
That's about as clean as it can be right now.

It's hard to see if the bigger ones are correct so I'll try to run a few tests to see if the right answers are coming up.

Thanks for doing this and the z180 one.  It's a pain, especially the larger ones.

I'm not sure if there is a way to do faster division using the multiplies.  A kind of binary search on the answer but that's for another time.

**Comment by feilipu** [comment]
Finally got around to testing with ticks for this and #820.
I'm not sure that the results are 100% valid, as leading zero elimination may be playing a part.
But, the outcome is nearly a 20x speed up for 16x16 multiplies.
A substantial improvement, I guess

```asm
;
; Assemble with z88dk for RC2014
; zcc +rc2014 --no-crt -clib=sdcc_iy -v -m --list z80mul.asm -o z80mul 
; appmake +glue --ihex --clean -b z80mul -c z80mul
; ticks -mz80 -start 04 -end 03 z80mul__.bin
;
; Assemble with z88dk for YAZ180
; zcc +yaz180 --no-crt -clib=sdcc_iy -v -m --list z80mul.asm -o z180mul
; appmake +glue --ihex --clean -b z180mul -c z180mul
; ticks -mz180 -start 04 -end 03 z180mul__.bin
;
; Assemble with z88dk for ZXNext
; zcc +zxn  --no-crt -clib=sdcc_iy -v -m --list z80mul.asm -o zxnmul
; appmake +glue --ihex --clean -b zxnmul -c zxnmul
; ticks -mz80-zxn -start 04 -end 03 zxnmul__.bin
;
;
; Function   Ticks = Z80     Z180   z80/z180        Z80-ZXN     z80/zxn
;
; l_mulu_32_16x16   3167      170     18.63x            161      19.67x
; l_mulu_64_64x64  11955     2851      4.19x           2881       4.15x
; l_mulu_72_64x8    1374      374      3.67x            337       4.08x
;
;------------------------------------------------------------------------------

SECTION code_user

EXTERN l_mulu_32_16x16, l_mulu_64_64x64, l_mulu_72_64x8

PUBLIC _main

_main:
;   call l_mulu_32_16x16        ; OR
;   call l_mulu_64_64x64        ; OR
    call l_mulu_72_64x8
    ret
```

**Comment by aralbrec** [comment]
Did you build the libraries with fast integer math enabled?  That has to be enabled in the clib_config file for the leading zero elimination to be enabled.

**Comment by aralbrec** [comment]
I'm a little surprised the 32x32 and above are that close if the 16x61 is 20x faster.  The small 32x32 multiply (not the fast integer math version) has to repeat about 30 lines of code 32 times (900+ lines) whereas the hw multiply ones are about 130 lines.  That's a 6-7x gap but maybe the instructions are more expensive on average so maybe 4x is not unreasonable.  On the zxn, the mlt is only 8 cycles though.

Anyway nice to see some tests.

**Comment by feilipu** [comment]
I've added the `l_mulu_16_16x16` multiply in too, and looked at the code run by ticks with `-trace` .
It seems that the `l_mulu_32_16x16` routine is a real sweet-spot for hardware support.

I can't see an error in method from these observations, so I think it reflects reality.
Also, my routines are brute force, and probably they could be finessed substantially.
An avenue for improvement.

**Pull request merged**
