### PR TITLE
zsdcc - r12419 - bugfix

### LINKED ISSUE #1792: (sdcc) Miscompilation from forum & z88dk 2.1.1 discussion
Nice succinct example from https://z88dk.org/forum/viewtopic.php?f=12&t=11537

```
#include <stdio.h>

typedef unsigned short uint16;

uint16 x, y;

static uint16 printHello() {
    printf("\nHello");
    return 1;
}

static uint16 hello(uint16 a, uint16 b) {
    uint16 result = 0;
    if(a + b > x - y){
        result = printHello();
    }
    return result;
}

void main() {
    x = 2000;
    y = 1000;
    hello(600,600);
}
```

Compilation yields (snipped to the problem bit):

```
        ld      hl,_y
        ld      a, (_x+0)
        sub     a, (hl)
        ld      h, a              <<<<<<< 
        ld      a, (_x+1)
        inc     hl
        sbc     a, (hl)
        ld      l, a
        ld      a, h
        sub     a, c
        ld      a, l
        sbc     a, b
        jr      NC,l_hello_00102

```

Compiling with --max-allocs-per-node0 works around this.

### LINKED ISSUE #1794: zsdcc compilation issue/error
Hi,

I think i may have identified a ZCC compiler error.  I recently attempted to recompile a project that i had not worked on for a few months - and noticed some tests were now failing.

I managed to track it down to an issue with CARRY FLAG/SBC handling.

## How to reproduce:

Compile the following `zcc +cpm -clib=sdcc_iy -S  -create-app test.c`

```
#include <stdlib.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

uint16_t p = 0x202;

void main() {
  if (p < 0x0200)
    printf("1. First time it does not evaluate to TRUE\r\n");
  else
    printf("2. First time it does evaluate to FALSE\r\n");

  if (p < 0x0200)
    printf("3. But now it incorrectly evaluates to TRUE\r\n");
  else
    printf("4. It should have been FALSE\r\n");
}
```

When you run the code, the first condition correctly evaluates to TRUE, but the same condition tested a second time, evaluates to FALSE

I get this output:

```
cpm --exec A

2. First time it does evaluate to FALSE
3. But now it incorrectly evaluates to TRUE
```

The assembly it produces for the condition is:
```
	ld	a,(_p + 1)
	sbc	a,0x02
	jr	NC,l_main_00102
```

Its using SBC, but it never clears the CARRY FLAG before the SBC, so its behaviour is a little unpredictable.

I reproduced this with commit #4f92db5666c994274057b33b0d2fee47c7e29354

I also tried this with different levels of optimisation.

If this is an issue, I not sure when it got introduced as I had not touch my project that is now erroring, for about 6 months.

Hope this makes sense and is helpful.

Dean

### PR DESCRIPTION
**Pull request by feilipu**
Updating sdcc addressing bugs.

Closes #1792
Closes #1794

Partial changelog from r12288 (previous zsdcc version).
```
2021-06-03 Philipp Klaus Krause <pkk AT spth.de>
	* src/SDCCast.c,
	  src/SDCCerr.c,
	  src/SDCCerr.h,
	  support/valdiag/tests/bug-2798.c:
	  Fix bug #2798.

2021-05-27 Philipp Klaus Krause <pkk AT spth.de>
	* src/z80/gen.c,
	  support/regression/tests/bug-3244.c:
	  Fix bug #3244.

2021-05-20 Philipp Klaus Krause <pkk AT spth.de>
	* support/regression/Makefile.in,
	  support/regression/ports/ucz180-resiy:
	  Test z180 port with --reserve-regs-iy.
	* sdcc/support/regression/ports/ucz80/spec.mk,
	  sdcc/support/regression/ports/ucr3ka/spec.mk:
	  Drop --profile option, so we get better coverage of tail call optimization.

2021-05-19 Philipp Klaus Krause <pkk AT spth.de>
	* src/z80/gen.c:
	  Partial fix for bug #3054.

2021-05-18 Philipp Klaus Krause <pkk AT spth.de>
	* src/z80/gen.c,
	  support/regression/tests/bug-3242.c:
	  Fix bug #3242.

2021-05-17 Philipp Klaus Krause <pkk AT spth.de>
	* src/SDCCpeeph.c,
	  src/pdk/peep.c,
	  src/stm8/peep.c,
	  src/z80/gen.c,
	  src/z80/peep.c,
	  support/regression/tests/bug-3239.c:
	  Fix bugs #3235, 3239.

2021-05-17 Philipp Klaus Krause <pkk AT spth.de>
	* src/z80/gen.c:
	  Fix a code generation bug in hl handling.

2021-05-17 Philipp Klaus Krause <pkk AT spth.de>
	* src/stm8/gen.c,
	  src/z80/gen.c:
	  Refactor __z88dk_callee support to allow other calling conventions to use callee stack cleanup.

2021-05-17 Philipp Klaus Krause <pkk AT spth.de>
	* src/SDCCicode.h,
	  src/SDCCicode.c,
	  src/SDCCsalloc.hpp,
	  src/stm8/gen.c,
	  src/z80/gen.c,
	  support/regression/tests/bug-3240.c:
	  Tail call optimization fixes for register parameters.

2021-05-14 Philipp Klaus Krause <pkk AT spth.de>
	* src/z80/gen.c,
	  src/stm8/gen.c:
	  Fix code generation bugs triggered by register arguments.

2021-05-14 Philipp Klaus Krause <pkk AT spth.de>
	* src/z80/gen.c:
	  Improve tail call optimization.

2021-05-14 Philipp Klaus Krause <pkk AT spth.de>
	* src/z80/gen.c:
	  Fix a bug in handling of register parameters to function calls via pointer.

2021-05-13 Philipp Klaus Krause <pkk AT spth.de>
	* src/z80/gen.c,
	  src/stm8/gen.c:
	  Fix handling of multiple register parameters.

2021-05-13 Philipp Klaus Krause <pkk AT spth.de>
	* src/z80/gen.c,
	  src/z80/ralloc.c:
	  Increase some regalloc_dry_run_cost penalties to avoid invalid allocation even when all alternatives result in expensive spilling.

2021-05-12 Philipp Klaus Krause <pkk AT spth.de>
	* src/z80/peep.c,
	  src/z80/gen.c:
	  Fixes for register parameter in a, l or hl.

2021-05-12 Philipp Klaus Krause <pkk AT spth.de>
	* src/z80/peep.c:
	  Fix bug #3234.

2021-05-12 Philipp Klaus Krause <pkk AT spth.de>
	* src/z80/gen.c,
	  src/z80/gen.h,
	  src/z80/main.c,
	  src/z80/peep.c:
	  Infrastructure for non-__z88dk_fastcall register arguments.

2021-05-09 Philipp Klaus Krause <pkk AT spth.de>
	* src/z80/gen.c,
	  src/stm8/gen.c:
	  Improve stack adjustment.

2021-05-09 Philipp Klaus Krause <pkk AT spth.de>
	* src/z80/gen.c,
	  support/regression/tests/bug-3231.c:
	  Fix bug #3231.

2021-05-08 Philipp Klaus Krause <pkk AT spth.de>
	* src/z80/gen.c,
	  support/regression/tests/bug-3230.c:
	  Fix bug #3230.

2021-05-07 Philipp Klaus Krause <pkk AT spth.de>
	* src/stm8/gen.c,
	  src/z80/gen.c,
	  support/regression/tests/bug-3229.c:
	  Fix bug #3229.

2021-05-07 Philipp Klaus Krause <pkk AT spth.de>
	* src/z80/gen.c:
	  Fix some bugs triggered by return values in other than the conventional registers.

2021-05-07 Philipp Klaus Krause <pkk AT spth.de>
	* src/z80/gen.c:
	  Fix a bug in handling of return values in bc.

2021-05-07 Philipp Klaus Krause <pkk AT spth.de>
	* src/stm8/gen.h,
	  src/stm8/gen.c,
	  src/stm8/peep.c,
	  src/z80/gen.h,
	  src/z80/gen.c,
	  src/z80/peep.c:
	  Deduplicate return value handling in peephole optimizer vs code generation.

```

### CODE REVIEW

**Comment by suborb** [comment]
@feilipu I'm afk at the moment, but soon....

**Comment by feilipu** [comment]
Please hold. Pending snap pass for added bug fix.
Will update shortly.

**Comment by feilipu** [comment]
I see [two green dots](http://sdcc.sourceforge.net/snap.php). 👍

**Comment by suborb** [comment]
I think we'll have to wait for #1809 to be fixed - I'm "ok" with known bugs (eg #1780 etc) but regressions just cause headaches.

**Comment by feilipu** [comment]
I've no further issue here. #1811 resolves my concern with r12419.
Good to go.

**Pull request merged**
