### PR TITLE
m32 - accuracy revisions

### PR DESCRIPTION
**Pull request by feilipu**
Revised the calculation of m32 derived functions, by building an internal 32-bit mantissa calculation path.
This was supported by just two intrinsic functions add, and multiply.
Alternate entries were made for either;
 - LHS IEEE - RHS expanded mantissa, or
 - LHS expanded mantissa - RHS expanded mantissa

From these two function sets divide (inverse), square root (inverse square root), and polynomial evaluation were reworked. Accuracy improved substantially.

The Hi-Tech C originated trigonometric and power functions are now better but, as the library functions rely on the provided coefficients, their accuracy is still pretty shite. Nothing I can do about that.

### CODE REVIEW

**Comment by suborb** [comment]
I think I'm missing something/or I've made a wonky merge.

I'm still struggling with division results,  x/x != 1.000000 which causes all sorts of grief when printing numbers. 

I can see some improvement/movement in the sin() - I'll take a look at re-implementing these with some proven series values/algorithms.

**Comment by feilipu** [comment]
No, I think your merge is probably OK. Divide is still not perfect. But the 32-bit mantissa revision has improved the accuracy by (about) two decimal places from where it was before.

The divide result now is as good as the Digi International claimed for their solution
*"Generally the basic functions are accurate within 1-3 counts of the floating mantissa."*

Adding further iterations to the N-R scheme doesn't improve accuracy. There would need to be many more bits in the mantissa calculation to achieve further improvement.

Here's some of my results for `n / n`, for reference, on a rc2014 soft multiply.
Are you seeing something similar?
```
float 1 m48: 1.000000 m32: 0.999988
float 2 m48: 1.000000 m32: 0.999988
float 3 m48: 1.000000 m32: 0.999988
float 4 m48: 1.000000 m32: 0.999988
float 5 m48: 1.000000 m32: 0.999999
float 6 m48: 1.000000 m32: 0.999988
float 7 m48: 1.000000 m32: 0.999999
float 8 m48: 1.000000 m32: 0.999988
float 9 m48: 1.000000 m32: 1.000000
float 10 m48: 1.000000 m32: 0.999999
float 11 m48: 1.000000 m32: 0.999993
float 12 m48: 1.000000 m32: 0.999988
float 13 m48: 1.000000 m32: 0.999993
float 14 m48: 1.000000 m32: 0.999999
float 15 m48: 1.000000 m32: 1.000000
float 16 m48: 1.000000 m32: 0.999988
float 17 m48: 1.000000 m32: 0.999999
float 18 m48: 1.000000 m32: 1.000000
float 19 m48: 1.000000 m32: 1.000000
float 20 m48: 1.000000 m32: 0.999999
float 21 m48: 1.000000 m32: 0.999997
float 22 m48: 1.000000 m32: 0.999993
float 23 m48: 1.000000 m32: 0.999989
float 24 m48: 1.000000 m32: 0.999988
float 25 m48: 1.000000 m32: 0.999989
float 26 m48: 1.000000 m32: 0.999993
float 27 m48: 1.000000 m32: 0.999997
float 28 m48: 1.000000 m32: 0.999999
float 29 m48: 1.000000 m32: 1.000000
float 30 m48: 1.000000 m32: 1.000000
float 31 m48: 1.000000 m32: 0.999999
float 32 m48: 1.000000 m32: 0.999988
```
But there is an issue which I haven't nailed down into either implementation or artefact at this stage. For some values of `n / n` (where the mantissa is almost empty) the accuracy becomes quite poor.
*One of these things is not like the others.*
```
float 57 m48: 1.000000 m32: 1.000000
float 58 m48: 1.000000 m32: 1.000000
float 59 m48: 1.000000 m32: 1.000000
float 60 m48: 1.000000 m32: 1.000000
float 61 m48: 1.000000 m32: 1.000000
float 62 m48: 1.000000 m32: 0.999999
float 63 m48: 1.000000 m32: 1.011465
float 64 m48: 1.000000 m32: 0.999988
float 65 m48: 1.000000 m32: 0.999993
float 66 m48: 1.000000 m32: 0.999996
float 67 m48: 1.000000 m32: 0.999998
float 68 m48: 1.000000 m32: 0.999999
float 69 m48: 1.000000 m32: 1.000000
float 70 m48: 1.000000 m32: 1.000000
float 71 m48: 1.000000 m32: 1.000000
float 72 m48: 1.000000 m32: 1.000000
```

**Comment by feilipu** [comment]
On fixing the Sine (etc) functions, I've finally found a [reference for converting](https://www.dragonwasrobot.com/mathematics/2015/08/03/an-introduction-to-horner-s-method.html) from polynomial coefficients to Horner's method coefficients, for the [Sine polynomial expansion](http://www.nabla.hr/CL-DerivativeG3.htm).

Looking forward to some high school maths next weekend. 😰

**Comment by suborb** [comment]
Great work @feilipu - I'll try it out this evening and then I can merge my monster PR.

We still need to do the newlib bindings - hopefully just updating the .lst files work.

It looks we've got n-body (multiplication based), spectral-norm (int -> float conversion based) and whetstone with previous results.

**Comment by suborb** [comment]
It's so close! 4.0 / 1.0 = 3.9999998 (0x407fffff)  4.0 / 2.0 = 1.9999999 (0x3fffffff)

I'm having real issues with the ftoa() implementation as a result - what are you using the print the numbers in your results?

**Comment by feilipu** [comment]
I think that may be related to rounding.

The Digi code does rounding twice, and I've followed their example (up to now). But I'm not sure this is correct. The result is that when calculating the denominator a lost bit could end up being larger than it should be by promotion of 256x or more! Also, there is repeated rounding so this situation can be amplified.

For example the 4 byte mantissa in an addition gets shifted right by 8 shifts and rounded.
`10000000 00000000 00000000 00000001 => 00000000 10000000 00000000 00000001 --------`
Then it gets normalised.
`00000000 10000000 00000000 00000001 => 10000000 00000000 00000001 00000000`
And the result is that least significant bit has too much weight.
`10000000 00000000 00000000 00000001 |= 10000000 00000000 00000001 00000000 `

I will check whether this is actually the problem, and if so rework the 32-bit mantissa add and multiply functions to NOT round, and just to round once when packing up.

**Comment by feilipu** [comment]
I've had a good look at this, and rounding in the N-M mantissa is not specifically the problem.

 > It's so close! 4.0 / 1.0 = 3.9999998 (0x407fffff) 4.0 / 2.0 = 1.9999999 (0x3fffffff)

Breaking this into its components, I find the inverse of `n` is exactly `1 / n`. So N-R is working correctly. 

The final multiply produces the variance. I've tried capturing all the bits for rounding away from zero, but either I've not done it right, or it is not working. I am seeing +-2 digits from the multiply function.

i.e. `16.000000` is between `15.999999` and `16.000002`.

> I'm having real issues with the ftoa() implementation as a result - what are you using the print the numbers in your results?

The newlib code for the conversion of `%f` seems to cope OK. I get solid numbers for the `4.0 / 1.0` question. Using d48 for compiler functions, not from m32, and zsdcc.
```c
    for (n = 1; n <= 255; n+=1)
    {
        floatl = (float)n*4.0;
        floatr = (float)n;

        result_m48 = floatl/floatr;

        resulta_m32 = fsinv(floatr);
        resultd_m32 = fsdiv(floatl,floatr);

        printf("float %u m48: %f m32a: %f m32d: %f\r\n", n, result_m48, resulta_m32, resultd_m32);
    }
```
B>ftest

float 1 m48: 4.000000 m32a: 1.000000 m32d: 4.000000
float 2 m48: 4.000000 m32a: 0.500000 m32d: 4.000000
float 3 m48: 4.000000 m32a: 0.333333 m32d: 4.000000
float 4 m48: 4.000000 m32a: 0.250000 m32d: 4.000000
float 5 m48: 4.000000 m32a: 0.200000 m32d: 4.000000
float 6 m48: 4.000000 m32a: 0.166667 m32d: 4.000000
float 7 m48: 4.000000 m32a: 0.142857 m32d: 4.000000
float 8 m48: 4.000000 m32a: 0.125000 m32d: 4.000000
float 9 m48: 4.000000 m32a: 0.111111 m32d: 4.000000
float 10 m48: 4.000000 m32a: 0.100000 m32d: 4.000000
float 11 m48: 4.000000 m32a: 0.090909 m32d: 4.000000
float 12 m48: 4.000000 m32a: 0.083333 m32d: 4.000000
float 13 m48: 4.000000 m32a: 0.076923 m32d: 4.000000
float 14 m48: 4.000000 m32a: 0.071429 m32d: 4.000000
float 15 m48: 4.000000 m32a: 0.066667 m32d: 4.000000
float 16 m48: 4.000000 m32a: 0.062500 m32d: 4.000000
float 17 m48: 4.000000 m32a: 0.058824 m32d: 4.000000
float 18 m48: 4.000000 m32a: 0.055556 m32d: 4.000000
float 19 m48: 4.000000 m32a: 0.052632 m32d: 4.000000
float 20 m48: 4.000000 m32a: 0.050000 m32d: 4.000000
float 21 m48: 4.000000 m32a: 0.047619 m32d: 4.000000
float 22 m48: 4.000000 m32a: 0.045455 m32d: 4.000000
float 23 m48: 4.000000 m32a: 0.043478 m32d: 4.000000
float 24 m48: 4.000000 m32a: 0.041667 m32d: 4.000000
float 25 m48: 4.000000 m32a: 0.040000 m32d: 4.000000
float 26 m48: 4.000000 m32a: 0.038462 m32d: 4.000000
float 27 m48: 4.000000 m32a: 0.037037 m32d: 4.000000
float 28 m48: 4.000000 m32a: 0.035714 m32d: 4.000000
float 29 m48: 4.000000 m32a: 0.034483 m32d: 4.000000
float 30 m48: 4.000000 m32a: 0.033333 m32d: 4.000000
float 31 m48: 4.000000 m32a: 0.032258 m32d: 4.000000
float 32 m48: 4.000000 m32a: 0.031250 m32d: 4.000000
etc forever...
```

**Pull request merged**
