### PR TITLE
z180 - integer math routines

### PR DESCRIPTION
**Pull request by feilipu**
Encouragement to complete the integer math routines using the z180 `mlt` instructions,
from #481 and #312.

I've had a go at the easy `24_16x8` and `40_32x8` routines. I think they're OK, but untested currently.
They should help string processing.

I also had another go at the `16_16x8` and I think I saved one instruction and two registers :champagne:
The difficult routines for `64_32x32`, and `64_64x64` are now done.

The linkages to the integer library are complete, and now for detailed test across the C library functions.

- [x] `l_mulu_16_8x8`
- [x] `l_mulu_16_16x8`
- [x] `l_mulu_16_16x16`
- [x] `l_mulu_24_16x8`
- [x] `l_mulu_32_16x16`
- [x] `l_mulu_32_32x32` (using `l0_mulu_32_32x32`)
- [x] `l_mulu_40_32x8`
- [x] `l_mulu_64_32x32` (using `l0_mulu_64_32x32`)
- [x] `l_mulu_64_64x64` (using `l0_mulu_64_32x32`and `l0_mulu_32_32x32`)
- [x] `l_mulu_72_64x8`

TODO file will be deleted later.
Just tracking the interfaces for the various routines and `TODO` done state.

### CODE REVIEW

**Comment by feilipu** [comment]
Moved the zxn and z180 integer math directories out of `~/small/`, and into the root directory.

Logic behind this is that the z180 implementation is actually not "small". It is actually closer to "fast", in that it is unrolled linear code. Probably the same will be true of the zxn implementation.

It turns out that having two multiply op codes `mlt bc` and `mlt de` with addition to the `hl` accumulator is pretty useful in practice. Being able to easily swap registers `ex bc,de` would help if z180 equivalent multiply opcodes don't become available on the zxn.

**Comment by feilipu** [comment]
For the [`72_64*8`](https://github.com/z88dk/z88dk/pull/820/files#diff-2a441018a24a35da4548e4c7d9a11892R25) and [`40_32*8`](https://github.com/z88dk/z88dk/pull/820/files#diff-7fd97a00bdefb112e2a88a5abde9dca6R25) routines extra effort was made to preserve `af'`, because these registers were not affected by the default small routines.

Is this really necessary?

**Comment by feilipu** [comment]
The work is finished and has been tested. It should be reviewed, but I think it is done.

**Comment by aralbrec** [comment]
Cheers @feilipu I will have a look soon.

The distinction between small and fast is the fast set includes code for leading zero elimination and unrolling which makes the implementation a lot bigger.

The register use contract (where af' is supposed to be unaffected) is also for the library.  These multiply functions are used by printf (through stdlib) and stdlib via the strtol, utoa family.  The multiplies are also used in other subroutines, eg, the sorting functions.  Really a find and an examination of affected files would have to be done to make sure it's ok to use af'.

**Comment by feilipu** [comment]
To avoid doubt around the `ex af,af` usage of the `72_64x8` and `40_32x8` routines, I've inspected everything that calls them, and everything that is called from these calling routines.
There are just the two below. Nothing they call uses `af'`.

```asm
PUBLIC __strtoul__
EXTERN l_valid_base, l_eat_ws, l_eat_sign, l_eat_digits, error_lzc
EXTERN l_neg_dehl, l_char2num, l_mulu_40_32x8, l_eat_base_prefix

PUBLIC __strtoull__
EXTERN l_valid_base, l_eat_ws, l_eat_sign, l_neg_64_dehldehl
EXTERN l_eat_base_prefix, l_char2num, error_llznc, l_mulu_72_64x8
EXTERN l_add_64_dehldehl_a, l_eat_digits, error_llzc
```
Reversing the inspection to find anything using `ex af,af`, it is only these library functions that mention `ex af,af'`. All other mentions are examples, or are relating to platform specifics.
None of these routines call anything related to the two relevant multiplies.

```
l/sdcc/____sdcc_ll_asr_hlix_a.asm:   ex af,af'
l/sdcc/____sdcc_ll_asr_hlix_a.asm:   ex af,af'
l/sdcc/____sdcc_ll_lsl_hlix_a.asm:   ex af,af'
l/sdcc/____sdcc_ll_lsl_hlix_a.asm:   ex af,af'
l/sdcc/____sdcc_ll_lsr_hlix_a.asm:   ex af,af'
l/sdcc/____sdcc_ll_lsr_hlix_a.asm:   ex af,af'
l/sdcc/__rlulonglong.asm:   ex af,af'
l/sdcc/__rlulonglong.asm:   ex af,af'
l/sdcc/__rlulonglong_callee.asm:   ex af,af'
l/sdcc/__rlulonglong_callee.asm:   ex af,af'
l/sdcc/__rlulonglong_callee.asm:   ex af,af'
l/sdcc/__rrslonglong.asm:   ex af,af'
l/sdcc/__rrslonglong.asm:   ex af,af'
l/sdcc/__rrslonglong_callee.asm:   ex af,af'
l/sdcc/__rrslonglong_callee.asm:   ex af,af'
l/sdcc/__rrslonglong_callee.asm:   ex af,af'
l/sdcc/__rrulonglong.asm:   ex af,af'
l/sdcc/__rrulonglong.asm:   ex af,af'
l/sdcc/__rrulonglong_callee.asm:   ex af,af'
l/sdcc/__rrulonglong_callee.asm:   ex af,af'
l/sdcc/__rrulonglong_callee.asm:   ex af,af'
l/sdcc/__sdcc_exit_div_64.asm:   ex af,af'
l/sdcc/__sdcc_exit_div_64.asm:   ex af,af'
l/sdcc/__sdcc_exit_div_64_callee.asm:   ex af,af'
l/sdcc/__sdcc_exit_div_64_callee.asm:   ex af,af'
l/sdcc/__sdcc_exit_mod_64.asm:   ex af,af'
l/sdcc/__sdcc_exit_mod_64.asm:   ex af,af'
l/sdcc/__sdcc_exit_mod_64_callee.asm:   ex af,af'
l/sdcc/__sdcc_exit_mod_64_callee.asm:   ex af,af'
stdio/z80/output_helpers/__stdio_printf_float_tail.asm:   ex af,af'
stdio/z80/output_helpers/__stdio_printf_float_tail.asm:   ex af,af'
stdio/z80/output_helpers/__stdio_printf_float_tail.asm:   ex af,af'
stdio/z80/output_helpers/__stdio_printf_float_tail.asm:   ex af,af'
stdio/z80/output_helpers/__stdio_printf_float_tail.asm:   ex af,af'
stdio/z80/output_helpers/__stdio_printf_float_tail.asm:   ex af,af'
stdio/z80/output_helpers/__stdio_printf_float_tail.asm:   ex af,af'
stdio/z80/output_helpers/__stdio_printf_float_tail.asm:   ex af,af'
stdlib/z80/__dtoa_asm_exit.asm:   ex af,af'
stdlib/z80/__dtoa_print.asm:   ex af,af'
stdlib/z80/__dtoh__.asm:   ex af,af'
stdlib/z80/__dtoh__.asm:   ex af,af'
stdlib/z80/asm_strtod.asm:   ex af,af'
stdlib/z80/asm_strtod.asm:   ex af,af'
```
I also note that the `64_64x64` multiply is specified affect `af'`, so that was not searched.

**Comment by feilipu** [comment]
Also @aralbrec if desired, I could convert these routines for the z80-zxn, by limiting to just the one multiply function. I'd have to test with the z180 op code, and then substitute the zxn op code before finalising the PR. Thoughts?

**Comment by feilipu** [comment]
Ok. Contract for `72_64x8` and `40_32x8` has been updated.
Please review and merge.

I'll open a new PR for the `z80-zxn` integer math routines.

**Comment by feilipu** [comment]
:wave: @aralbrec

**Comment by feilipu** [comment]
> I made some minor changes to completely separate the z180 math from the z80 math.

Thanks. That's much cleaner.

See also this question #835 about `IF ... ELIF ... ENDIF`

It might make the `IF __CPU_Z180__ && ((__CLIB_OPT_IMATH = 0) || (__CLIB_OPT_IMATH = 100))` lines more legible, once the `__CPU_Z80_ZXN__`, and Rabbit processor alternatives are handled, too.

**Comment by suborb** [comment]
@aralbrec I need to check to confirm but I do remember spending a bit of time of z180 support so I think it does.

**Pull request merged**
