### PR TITLE
YAZ180 / RC2014 - minor updates / edits

### PR DESCRIPTION
**Pull request by feilipu**
A couple of minor edits to these two machines.

On the RC2014, I remembered how to stop the SIO bouncing the final byte interrupt. Fixed.

For the YAZ180, I've built both yabios, and z88dk examples successfully with these last few edits. And updated the yabios include file now that the [yabios is "stand-alone"](https://github.com/feilipu/yaz180/commit/4dc548e82589e65f77797c8421c38f2ab780ff1f) from z88dk.

### CODE REVIEW

**Comment by feilipu** [comment]
Hmm. Travis burp...

**Comment by aralbrec** [comment]
master branch is broken -- a missing crt for the m5 target in the classic library.
Wait a bit and see if it clears up

**Comment by suborb** [comment]
There’s a windows path causing problems. I’ll fix it in a bit.

**Comment by suborb** [comment]
Deburped, you'll need to merge master.

**Pull request merged**
